### ISSUE TITLE
My logo proposal for Travel-It 

### ISSUE THREAD

**Issue by CallMeFib3r** [iamank1t/travel-it-iOS#1]
Hi, 
I created a brand new logo for your project. Here's a quick preview.
![travelit](https://user-images.githubusercontent.com/37731582/38039090-c9ddd046-32ac-11e8-88fe-5547a254ed8f.png)

**Comment by CallMeFib3r** [comment]
The entire contribution can be found over here.
[https://utopian.io/utopian-io/@callmefib3r/logo-proposal-for-travel-it-ios-app](url)

**Comment by iamank1t** [comment]
Thanks for the contribution.
